# Generated by Django 3.2.14 on 2022-07-27 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demopyidzapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='position',
            new_name='leagueposition',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='teamname',
        ),
    ]
