# Generated by Django 3.2.14 on 2022-07-27 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demopyidzapp', '0003_auto_20220727_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teamname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='leagueposition',
            new_name='position',
        ),
    ]
