# Generated by Django 3.2.14 on 2022-08-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demopyidzapp', '0004_auto_20220727_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
